import { cp, mkdir, rm, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dist = join(root, 'dist');

function readText(name, fallback) {
  const value = process.env[name];
  return typeof value === 'string' && value.trim() ? value.trim() : fallback;
}

function parseLinks() {
  const raw = process.env.DASH_LINKS;
  if (!raw || !raw.trim()) return [];

  let parsed;
  try {
    parsed = JSON.parse(raw);
  } catch (error) {
    throw new Error(`DASH_LINKS 不是合法 JSON：${error.message}`);
  }

  if (!Array.isArray(parsed)) {
    throw new Error('DASH_LINKS 必须是 JSON 数组，例如 [{"title":"Service","url":"https://example.com"}]');
  }

  return parsed.map((item, index) => {
    if (!item || typeof item !== 'object' || Array.isArray(item)) {
      throw new Error(`DASH_LINKS[${index}] 必须是对象。`);
    }

    const title = String(item.title ?? '').trim();
    const url = String(item.url ?? '').trim();

    if (!title) throw new Error(`DASH_LINKS[${index}].title 不能为空。`);
    if (!url) throw new Error(`DASH_LINKS[${index}].url 不能为空。`);

    let parsedUrl;
    try {
      parsedUrl = new URL(url);
    } catch {
      throw new Error(`DASH_LINKS[${index}].url 不是有效网址：${url}`);
    }

    if (!['http:', 'https:'].includes(parsedUrl.protocol)) {
      throw new Error(`DASH_LINKS[${index}].url 只支持 http/https：${url}`);
    }

    const normalized = { title, url };

    for (const field of ['description', 'icon', 'accent', 'badge']) {
      if (item[field] !== undefined && item[field] !== null && String(item[field]).trim()) {
        normalized[field] = String(item[field]).trim();
      }
    }

    if (item.category !== undefined && item.category !== null) {
      const isArray = Array.isArray(item.category);
      const values = isArray ? item.category : [item.category];

      if (values.some(value => typeof value !== 'string')) {
        throw new Error(`DASH_LINKS[${index}].category 必须是字符串或字符串数组。`);
      }

      const categories = [...new Set(values.map(value => value.trim()).filter(Boolean))];
      if (categories.length) {
        normalized.category = isArray ? categories : categories[0];
      }
    }

    return normalized;
  });
}

const config = {
  siteTitle: readText('DASH_SITE_TITLE', 'Dash'),
  description: readText('DASH_DESCRIPTION', '把常用服务放在一个安静、好找的地方。'),
  footer: readText('DASH_FOOTER', 'Dash · Personal Navigation'),
  links: parseLinks()
};

await rm(dist, { recursive: true, force: true });
await mkdir(dist, { recursive: true });
await cp(join(root, 'index.html'), join(dist, 'index.html'));
await cp(join(root, 'assets'), join(dist, 'assets'), { recursive: true });

const generated = `// Generated by scripts/build.mjs at deploy time. Do not edit.\nwindow.DASH_CONFIG = ${JSON.stringify(config, null, 2)};\n`;
await writeFile(join(dist, 'config.js'), generated, 'utf8');

console.log(`Dash build complete: ${config.links.length} link(s) generated.`);